name: Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set Up Python Tooling
        uses: ./.github/workflows/setup

      - name: Build
        run: uv build

      - name: Publish
        run: uv publish
